### ISSUE TITLE
Create separate page for each Relaton processor, and write out how to cite (with examples of document identifiers)

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton.github.io#35]
Create separate page for each Relaton processor, and write out how to cite (with examples of document identifiers)

**Comment by ronaldtse** [comment]
@andrew2net can you please help with this? We can add a separate documentation page within each gem if needed.

**Comment by ronaldtse** [comment]
* https://github.com/relaton/relaton.github.io/issues/35

**Comment by andrew2net** [comment]
@ronaldtse do we really need to create separate pages? There are almost empty gems' pages already. https://www.relaton.org/software/relaton-iso/

**Comment by ronaldtse** [comment]
@andrew2net yes. We need to.
