### ISSUE TITLE
Move relaton.org to GitHub Pages

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton.github.io#42]
Just like https://github.com/plurimath/plurimath.org/issues/1

We have api.relaton.org, so we must keep the relaton.org DNS at Route53.

**Comment by kwkwan** [comment]
Hi @ronaldtse I cannot access the Setting page, please grant me as admin to perform the migration.  Thanks!

**Comment by ronaldtse** [comment]
@kwkwan fixed. Thanks!
