### ISSUE TITLE
Gemfile.lock is missing

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton.github.io#55]
This means site builds can break even if nothing changed.

**Comment by ronaldtse** [comment]
We don't want Gemfile.lock checked in.

**Comment by strogonoff** [comment]
This same issue has been reliably coming back to cause broken builds and divert work efforts from pressing projects at most inconvenient times. What justification is there to go against the best practices *and* our own empirical experience, and to not have the lockfile checked in?

**Comment by CAMOBAP** [comment]
@strogonoff to be on the same page which gem/repository we are talking?

**Comment by ronaldtse** [comment]
This issue is not quite necessary here, closing.
